services:
  - type: web
    name: erpsdksolution
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__EFDBContext
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
