services:
  - type: web
    name: erpsdksolution
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__EFDBContext
        value: "Server=db63574.public.databaseasp.net;Database=db63574;User Id=db63574;Password=B#e3fG5!4r%A;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True;"
      - key: ConnectionStrings__DefaultConnection
        value: "Server=db63574.public.databaseasp.net;Database=db63574;User Id=db63574;Password=B#e3fG5!4r%A;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True;"
